# Generated by Django 2.1 on 2018-08-12 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PizzaSearch', '0003_auto_20180808_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='price',
        ),
    ]
