# Generated by Django 2.1 on 2018-08-18 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PizzaSearch', '0006_auto_20180815_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=300, null=True, verbose_name='Состав')),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/', verbose_name='Изображение')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizzas_check', to='PizzaSearch.Shop', verbose_name='ID магазина')),
            ],
            options={
                'verbose_name': 'Пицца',
                'verbose_name_plural': 'Пиццы',
            },
        ),
        migrations.AddField(
            model_name='pizza',
            name='on_sale',
            field=models.BooleanField(default=True, verbose_name='В продаже'),
        ),
    ]
